def delete(pattern)
  files = Dir[pattern]
  rm(files, verbose: true) unless files.empty?
end

desc "Test Task"
task :test2 do
  # delete 'hello.a'
  # `rm hello.a`
  str = `rspec *_spec.rb`
  puts str
  # puts "test"
end

require "rake/clean"

require 'rake/testtask'
Rake::TestTask.new do |t|
      t.libs << "test"
      t.test_files = FileList['*_test.rb']
      t.verbose = true
end
